# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'venndor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for venndor
    pod 'GoogleMaps'
    pod 'SlackTextViewController'
    pod 'ImagePicker', '1.2'

  target 'venndorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'venndorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
